function pickMovie() {
    var nowPlaying = [
  "Alberto Scorfano from Luca",
  "Abby Mallard from Chicken Little",
  "Abigail Gabble from The Aristocats",
  "Abu from Aladdin",
  "Achilles from The Hunchback of Notre Dame",
  "Adella from The Little Mermaid",
  "Adelaide from The Aristocats",
  "Adorabeezle Winterpop from Wreck-It Ralph",
  "The Agent from Bolt",
  "Agent Wendy Pleakley from Lilo & Stitch",
  "Ajax the Gorilla from Donald Duck and the Gorilla",
  "Akela from The Jungle Book",
  "Al the Alligator from Lady and the Tramp",
  "Aladar from Dinosaur",
  "Aladdin from Aladdin",
  "Alameda Slim from Home on the Range",
  "Alan-a-Dale from Robin Hood",
  "Alana from The Little Mermaid",
  "Albus Duckweed from Amphibia",
  "Alcmene from Hercules",
  "Alfonso Dolittle from Star vs. the Forces of Evil",
  "Alice from Alice in Wonderland",
  "Alice Bluebonnet from Make Mine Music",
  "Alice's Sister from Alice in Wonderland",
  "Amelia Gabble from The Aristocats",
  "Amity Blight from The Owl House",
  "Amos Slade from The Fox and the Hound",
  "Amphitryon from Hercules",
  "Anastasia Tremaine from Cinderella",
  "Andrea Davenport from The Ghost and Molly McGee",
  "Andrina from The Little Mermaid",
  "Andromeda from Big City Greens",
  "Angie Diaz from Star vs. the Forces of Evil",
  "Angus MacBadger from The Adventures of Ichabod and Mr. Toad",
  "Animal from Muppet Babies",
  "Anita Radcliffe from 101 Dalmatians",
  "Anna from Frozen",
  "Anne Boonchuy from Amphibia",
  "Annette from Lady and the Tramp II: Scamp's Adventure",
  "April from House of Mouse",
  "Apollo from Hercules",
  "Aquata from The Little Mermaid",
  "Aracuan Bird from The Three Caballeros",
  "The Archdeacon from The Hunchback of Notre Dame",
  "Archimedes Q. Porter from Tarzan",
  "Archimedes from The Sword in the Stone",
  "Ariel from The Little Mermaid",
  "Arista from The Little Mermaid",
  "Armoire from Beauty and the Beast",
  "Arthur/Wart from The Sword in the Stone",
  "Arthur from Jungle Cubs",
  "Assistant Mayor Dawn Bellwether from Zootopia",
  "Atka from Brother Bear 2",
  "Atropos from Hercules",
  "Attina from The Little Mermaid",
  "Audrey the Chicken from Home on the Range",
  "Audrey Ramirez from Atlantis: The Lost Empire",
  "Augustus \"Gus\" Porter from The Owl House",
  "Aunt Sarah from Lady and the Tramp",
  "Aunt Siqiniq from Brother Bear 2",
  "Aunt Taqqiq from Brother Bear 2",
  "Aurora from Sleeping Beauty",
  "Axe from Beauty and the Beast: The Enchanted Christmas",
  "B.E.N. from Treasure Planet",
  "Babette from Beauty and the Beast",
  "Baby Red Bird from Mickey Mouse Clubhouse",
  "Baby Sinclair from Dinosaurs",
  "Babyface Beagle from DuckTales",
  "Backwoods Beagle from DuckTales",
  "Bacon Beagle from DuckTales",
  "Baggy Beagle from DuckTales",
  "Bagheera from The Jungle Book",
  "Baileywick from Sofia the First",
  "Baker from Beauty and the Beast",
  "Baker from Cinderella II: Dreams Come True",
  "Ballerina from Fantasia 2000",
  "Baloo Bear from The Jungle Book",
  "Bambi from Bambi",
  "Bambi's Mother from Bambi",
  "Banzai from The Lion King",
  "Bankjob Beagle from DuckTales",
  "Bartholomew from The Great Mouse Detective",
  "Barley Lightfoot from Onward",
  "Bashful from Snow White and the Seven Dwarfs",
  "Basil of Baker Street from The Great Mouse Detective",
  "Bat Queen from The Owl House",
  "Baylene from Dinosaur",
  "Baymax from Big Hero 6",
  "Beaker from Muppet Babies",
  "Bear from Bedknobs and Broomsticks",
  "Beary Barrington from The Country Bears",
  "Beast from Beauty and the Beast",
  "Beaver from Lady and the Tramp",
  "Becky from Finding Dory",
  "Bella from Mickey Mouse Clubhouse",
  "Belle from Beauty and the Beast",
  "Ben from Pocahontas",
  "Ben Ali Gator from Fantasia",
  "Benjamin Clawhauser from Zootopia",
  "Benny from Big City Greens",
  "Bent-Tail the Coyote from The Legend of Coyote Rock",
  "Bent-Tail Junior from Sheep Dog",
  "Bentina Beakley from DuckTales",
  "Beret Girl from An Extremely Goofy Movie",
  "Berlioz from The Aristocats",
  "Bernard from The Rescuers",
  "Big Al from The Country Bears",
  "Big Bad Wolf from Three Little Pigs",
  "Big Mama from The Fox and the Hound",
  "Bigtime Beagle from DuckTales",
  "Bill Green from Big City Greens",
  "Bill the Lizard from Alice in Wonderland",
  "Billy Boss from The Aristocats",
  "Billy Bones from Treasure Planet",
  "Bimbette from Beauty and the Beast",
  "Binkie Muddlefoot from Darkwing Duck",
  "Binky Beagle from DuckTales",
  "Black Bart from The Sword in the Stone",
  "Blarney from Dinosaurs",
  "Blake from Bolt",
  "Blaze from Tinker Bell and the Lost Treasure",
  "Blue Fairy from Pinocchio",
  "Bobble from Disney Fairies",
  "Bog from Amphibia",
  "Bolt from Bolt",
  "Bomber Beagle from DuckTales",
  "Bonnie Hopps from Zootopia",
  "Bookseller from Beauty and the Beast",
  "Boomer from The Fox and the Hound",
  "Boone Wiseman from Penn Zero: Part-Time Hero",
  "Bonkers D. Bobcat from Bonkers",
  "Boscha from The Owl House",
  "Boun from Raya and the Last Dragon",
  "Bouncer Beagle from DuckTales",
  "Bowler Hat Guy from Meet the Robinsons",
  "Br'er Bear from Song of the South",
  "Br'er Fox from Song of the South",
  "Br'er Frog from Song of the South",
  "Br'er Rabbit from Song of the South",
  "Braddock from Amphibia",
  "Bradley P. \"B.P.\" Richfield from Dinosaurs",
  "Bradley \"Brad\" Buttowski from Kick Buttowski: Suburban Daredevil",
  "Bradley Uppercrust III from An Extremely Goofy Movie",
  "Brett from Big City Greens",
  "Brittney Wong from Star vs. the Forces of Evil",
  "Brudo Avarius from Star vs. the Forces of Evil",
  "Bruno the Dog from Cinderella",
  "Bruton from Dinosaur",
  "Brutus and Nero from The Rescuers",
  "Buck from Home on the Range",
  "Buck Cluck from Chicken Little",
  "Buck Leatherleaf from Amphibia",
  "Bucky Bug from Silly Symphonies",
  "Bucky Oryx-Antlerson from Zootopia",
  "Bucky the Squirrel from The Emperor's New Groove",
  "Buff Frog from Star vs. the Forces of Evil",
  "Buford the Cook from The Princess and the Frog",
  "Buford Van Stomm from Phineas and Ferb",
  "Bugle Beagle from DuckTales",
  "Bunsen Honeydew from Muppet Babies",
  "Burger Beagle from DuckTales",
  "Butch the Bulldog from Bone Trouble",
  "Butcher Boy from Ralph Breaks the Internet",
  "Buzzie the Vulture from The Jungle Book",
  "Cadpig from 101 Dalmatians: The Series",
  "Calliope from Hercules",
  "Camilia Noceda from The Owl House",
  "Camilia the Chicken from Muppet Babies",
  "Candace Flynn from Phineas and Ferb",
  "Candlehead from Wreck-It Ralph",
  "The Captain from 101 Dalmatians",
  "Captain Amelia from Treasure Planet",
  "Captain Bufo from Amphibia",
  "Captain Grime from Amphibia",
  "Captain Hook from Peter Pan",
  "Captain John Smith from Pocahontas",
  "Captain Phoebus from The Hunchback of Notre Dame",
  "Carl the Robot from Meet the Robinsons",
  "Carlotta the Maid from The Little Mermaid",
  "The Carpenter from Alice in Wonderland",
  "Casey Junior from Dumbo",
  "Cass Hamada from Big Hero 6",
  "Cassandra/Cass from Rapunzel's Tangled Adventure",
  "The Caterpillar from Alice in Wonderland",
  "Catty the Elephant from Dumbo",
  "Cedric the Sorcerer from Sofia the First",
  "Chaca from The Emperor's New Groove",
  "Chair Mouse from The Rescuers",
  "Chainsaw from Goof Troop",
  "Charlene Fiona Sinclair from Dinosaurs",
  "Charlotte La Bouff from The Princess and the Frog",
  "Cheetata and Cheetato from Timon and Pumbaa",
  "Chef Bouche from Beauty and the Beast",
  "Chef Louis from The Little Mermaid",
  "Charles Muntz from UP",
  "Chernabog from Fantasia",
  "Cheshire Cat from Alice in Wonderland",
  "Chi-Fu from Mulan",
  "Chicha from The Emperor's New Groove",
  "Chicken Little from Chicken Little",
  "Chief from The Fox and the Hound",
  "Chief Benja from Raya and the Last Dragon",
  "Chief Bogo from Zootopia",
  "Chief Powhatan from Pocahontas",
  "Chien-Po from Mulan",
  "Chip from Private Pluto",
  "Chip Whistler from Big City Greens",
  "Chip Potts from Beauty and the Beast",
  "Christopher Robin from Winnie the Pooh and the Honey Tree",
  "Chuck from Amphibia",
  "Cinderella from Cinderella",
  "Circus Animals from Dumbo",
  "Clank from Disney Fairies",
  "Clara Cluck from Orphan's Benefit",
  "Clarabelle Cow from Plane Crazy",
  "Clarence Francis \"Kick\" Buttowski from Kick Buttowski: Suburban Daredevil",
  "Clayton from Tarzan",
  "Cleo from Pinocchio",
  "Clio from Hercules",
  "Cloak and Dagger from The Little Mermaid II: Return to the Sea",
  "Clopin Trouillefou from The Hunchback of Notre Dame",
  "Clotho from Hercules",
  "Clover from Sofia the First",
  "The Coachman from Pinocchio",
  "Cobra Bubbles from Lilo & Stitch",
  "Codfish from Bedknobs and Broomsticks",
  "Cody from The Rescuers Down Under",
  "Cogsworth from Beauty and the Beast",
  "Colette from Lady and the Tramp II: Scamp's Adventure",
  "The Colonel from 101 Dalmatians",
  "Colonel Hathi from The Jungle Book",
  "Commander Lyle Rourke from Atlantis: The Lost Empire",
  "Commander Peepers from Wander Over Yonder",
  "Cookie from Atlantis: The Lost Empire",
  "Copper from The Fox and the Hound",
  "Cornelius Robinson from Meet the Robinsons",
  "Cousin Randy from The Princess and the Frog",
  "Crane from Belle's Magical World",
  "Creeper from The Black Cauldron",
  "Cricket Green from Big City Greens",
  "Cri-Kee from Mulan",
  "The Crocodile (Tick Tock) from Peter Pan",
  "Cruella de Vil from 101 Dalmatians",
  "Crumbelina DiCaramello from Wreck-It Ralph",
  "Cubby from Peter Pan",
  "Cyril Proudbottom from The Adventures of Ichabod and Mr. Toad",
  "Daisy Duck from Mr. Duck Steps Out",
  "Dale from Private Pluto",
  "Dallben from The Black Cauldron",
  "Dandy (Jim) Crow from Dumbo",
  "Dang Hu from Raya and the Last Dragon",
  "Danielle from Lady and the Tramp II: Scamp's Adventure",
  "Danny from Return to Never Land",
  "Darby from My Friends Tigger & Pooh",
  "Darling from Lady and the Tramp",
  "Darryl McGee from The Ghost and Molly McGee",
  "Dash Parr from The Incredibles",
  "David Kawena from Lilo & Stitch",
  "Deacon (Preacher) Crow from Dumbo",
  "Delilah Dalmatian from 101 Dalmatian Street (series)",
  "Della Duck from DuckTales",
  "Demetrius from Hercules",
  "Denahi from Brother Bear",
  "Dennis Avarius from Star vs. the Forces of Evil",
  "Derek Blunt from Darkwing Duck",
  "DeSoto from Oliver & Company",
  "Dewey from Donald's Nephews",
  "Dex Barrington from The Country Bears",
  "Diablo the Raven from Sleeping Beauty",
  "Digger the Mole from The Rescuers",
  "Dijon the Thief from DuckTales",
  "Dinah the Cat from Alice in Wonderland",
  "Dinah the Dachshund from The Sleepwalker",
  "Dinky from The Fox and the Hound",
  "Dipper Pines from Gravity Falls",
  "The Director from Bolt",
  "Dixie from The Fox and the Hound 2",
  "Dizzie the Vulture from The Jungle Book",
  "Djali from The Hunchback of Notre Dame",
  "Doc from Snow White and the Seven Dwarfs",
  "Doctor Mouse from The Rescuers Down Under",
  "Dodger from Oliver & Company",
  "The Dodo from Alice in Wonderland",
  "The Dog Catcher from Lady and the Tramp II: Scamp's Adventure",
  "Doli from The Black Cauldron",
  "Dolly Dalmatian from 101 Dalmatian Street (series)",
  "Don Karnage from TaleSpin",
  "Donald Duck from The Wise Little Hen",
  "Doofus Drake from DuckTales",
  "The Doorknob from Alice in Wonderland",
  "The Doorman from Cinderella",
  "Dopey from Snow White and the Seven Dwarfs",
  "Dopey (Straw Hat) Crow from Dumbo",
  "Doris from Meet the Robinsons",
  "The Dormouse from Alice in Wonderland",
  "Double Dan from Ralph Breaks the Internet",
  "Doug Dalmatian from 101 Dalmatian Street (series)",
  "Doug Ramses from Zootopia",
  "Dr. Calico from Bolt",
  "Dr. David Q. Dawson from The Great Mouse Detective",
  "Dr. Delbert Doppler from Treasure Planet",
  "Dr. Facilier from The Princess and the Frog",
  "Dr. Forrester from Bolt",
  "Dr. Heinz Doofenshmirtz from Phineas and Ferb",
  "Dr. Jacques von Hämsterviel from Stitch! The Movie",
  "Dr. Joshua Sweet from Atlantis: The Lost Empire",
  "Dr. Jumba Jookiba from Lilo & Stitch",
  "Dr. Reginald Bushroot from Darkwing Duck",
  "Dr. Teeth from Muppet Babies",
  "Drake Mallard (Darkwing Duck) from Darkwing Duck",
  "Drew Lipsky / Dr. Drakken from Kim Possible",
  "Drizella Tremaine from Cinderella",
  "Duchess from The Aristocats",
  "Duchess from One Hundred and One Dalmatians",
  "Duckworth from DuckTales",
  "Duke from Fantasia 2000",
  "Duke of Weselton from Frozen",
  "Duke Weaselton from Zootopia",
  "Dumbo from Dumbo",
  "Duncan from Wreck-It Ralph",
  "Dylan Dalmatian from 101 Dalmatian Street (series)",
  "Earl Sneed Sinclair from Dinosaurs",
  "Eclipsa Butterfly from Star vs. the Forces of Evil",
  "Ed from The Lion King",
  "Edalyn \"Eda\" Clawthorne from The Owl House",
  "Edgar Balthazar the Butler from The Aristocats",
  "Edric Blight from The Owl House",
  "Edward from Return to Never Land",
  "Eema from Dinosaur",
  "Eeyore from Winnie the Pooh and the Honey Tree",
  "Einstein from Oliver & Company",
  "El Capitan from DuckTales",
  "Eli \"Big Daddy\" La Bouff from The Princess and the Frog",
  "Ellie Mae from The Rescuers",
  "Ellie Fredricksen from Up",
  "Elliott from Pete's Dragon",
  "Elmer Elephant from Silly Symphonies",
  "Elsa from Frozen",
  "Emira Blight from The Owl House",
  "Emmitt Otterton from Zootopia",
  "Emo Kid from Kick Buttowski: Suburban Daredevil",
  "Emperor Awesome from Wander Over Yonder",
  "Emperor Belos from The Owl House",
  "Emperor of China from Mulan",
  "The Enchantress from Beauty and the Beast: The Enchanted Christmas",
  "Ercole Visconti from Luca",
  "Esmeralda from The Hunchback of Notre Dame",
  "Ethyl Hinkleman Phillips from Dinosaurs",
  "Eudora from The Princess and the Frog",
  "Eugene Fitzherbert from Tangled",
  "Evangeline from The Princess and the Frog",
  "EVE from WALL-E",
  "Evil Queen from Snow White and the Seven Dwarfs",
  "Evinrude from The Rescuers",
  "Fa Li from Mulan",
  "Fa Zhou from Mulan",
  "Fagin from Oliver & Company",
  "Fairy Godmother from Cinderella",
  "Fairy Mary from Disney Fairies",
  "Faline from Bambi",
  "Fall-Apart Rabbit from Bonkers",
  "Faloo from The Rescuers Down Under",
  "Fat Cat from Chip 'n Dale Rescue Rangers",
  "Father Wolf from The Jungle Book",
  "Fats Crow from Dumbo",
  "Fauna from Sleeping Beauty",
  "Felicia the Cat from The Great Mouse Detective",
  "Felony from Ralph Breaks the Internet",
  "Fens from Amphibia",
  "Fenton Crackshell (Gizmoduck) from DuckTales",
  "Fenton Q. Harcourt from Atlantis: The Lost Empire",
  "Ferb Fletcher from Phineas and Ferb",
  "Ferdie Fieldmouse from Mickey's Steam Roller",
  "Ferdinand the Bull from Silly Symphonies",
  "Ferguson O'Durguson from Star vs. the Forces of Evil",
  "Fflewddur Fflam from The Black Cauldron",
  "Fidget from The Great Mouse Detective",
  "Fiddler Pig from Three Little Pigs",
  "Fife the Piccolo from Beauty and the Beast: The Enchanted Christmas",
  "Fifer Pig from Three Little Pigs",
  "Fifi the Featherduster from Beauty and the Beast",
  "Figaro the Cat from Pinocchio",
  "Figment from Journey into Imagination with Figment",
  "Finnick from Zootopia",
  "First Ancestor Fa from Mulan",
  "The Firebird from Fantasia 2000",
  "Fish Out of Water from Chicken Little",
  "Fix-It Felix, Jr. from Wreck-It Ralph",
  "Flaps the Vulture from The Jungle Book",
  "Flash from Zootopia",
  "Flintheart Glomgold from DuckTales",
  "Flit from Pocahontas",
  "Flora from Sleeping Beauty",
  "Flotsam and Jetsam from The Little Mermaid",
  "Flounder from The Little Mermaid",
  "Flower from Bambi",
  "Flunkey the Baboon from The Jungle Book",
  "Footman from Cinderella",
  "Forte the Pipe Organ from Beauty and the Beast: The Enchanted Christmas",
  "Foxy Loxy from Chicken Little",
  "Fozzie Bear from Muppet Babies",
  "Fran from Higglytown Heroes",
  "Francis from Oliver & Company",
  "Francis Johanna \"Fran\" Phillips Sinclair from Dinosaurs",
  "Francois from Lady and the Tramp II: Scamp's Adventure",
  "Francois from The Rescuers Down Under",
  "Frank from The Rescuers Down Under",
  "Frankie the Frog from Meet the Robinsons",
  "Franny Robinson from Meet the Robinsons",
  "Fred from Big Hero 6",
  "Friar Tuck from Robin Hood",
  "Friend Owl from Bambi",
  "Frou-Frou from The Aristocats",
  "Gadget Hackwrench from Chip 'n Dale Rescue Rangers",
  "Gaetan \"Mole\" Moliére from Atlantis: The Lost Empire",
  "Captain Gantu from Lilo & Stitch",
  "Gaston from Beauty and the Beast",
  "Gazelle from Zootopia",
  "General Hologram from Wreck-It Ralph",
  "General Li from Mulan",
  "General Yunan from Amphibia",
  "Genie from Aladdin",
  "Geoff from The Ghost and Molly McGee",
  "George Darling from Peter Pan",
  "Georges Hautecourt from The Aristocats",
  "Georgette from Oliver & Company",
  "Geppetto from Pinocchio",
  "The Ghost Council from The Ghost and Molly McGee",
  "Giddy the Elephant from Dumbo",
  "Gideon from Pinocchio",
  "Giselle from Enchanted",
  "Giulia from Luca",
  "Gladstone Gander from DuckTales",
  "Gliss from Secret of the Wings",
  "Glittering Goldie from DuckTales",
  "Globgor Butterfly from Star vs. the Forces of Evil",
  "Gloria Sato from Big City Greens",
  "Glossaryck from Star vs. the Forces of Evil",
  "Gloyd Orangeboar from Wreck-It Ralph",
  "Go Go Tomago from Big Hero 6",
  "Goob from Meet the Robinsons",
  "Goofy from Mickey's Revue",
  "Goosey Loosey from Chicken Little",
  "Gopher from Winnie the Pooh and the Honey Tree",
  "Gordie Gibble from Kick Buttowski: Suburban Daredevil",
  "Gosalyn Mallard from Darkwing Duck",
  "Governor John Ratcliffe from Pocahontas",
  "Grace from Home on the Range",
  "Gramma Alice from Big City Greens",
  "Gramma Tala from Moana",
  "Gramps from The Rescuers",
  "Grand Councilwoman from Lilo & Stitch",
  "The Grand Duke from Cinderella",
  "Grandma Duck from This is Your Life, Donald Duck",
  "Grandma Nin from The Ghost and Molly McGee",
  "Grandmother Fa from Mulan",
  "Grandmother Willow from Pocahontas",
  "Great Prince of the Forest from Bambi",
  "Grimsby from The Little Mermaid",
  "Grumpy from Snow White and the Seven Dwarfs",
  "Grunkle Stan from Gravity Falls",
  "Gunther Magnuson from Kick Buttowski: Suburban Daredevil",
  "Gurgi from The Black Cauldron",
  "Gus Lollygagger from Cinderella",
  "Gus Goose from Donald's Cousin Gus",
  "Gyro Gearloose from DuckTales",
  "Hades from Hercules",
  "Hands from Treasure Planet",
  "Hannibal McFist from Randy Cunningham: 9th Grade Ninja",
  "Happy from Snow White and the Seven Dwarfs",
  "Harold the Seahorse from The Little Mermaid",
  "Haroud Hazi Bin from Aladdin (TV series)",
  "Harold \"Harry\" Buttowski from Kick Buttowski: Suburban Daredevil",
  "Harvey Fenner from The Princess and the Frog",
  "Headless Horseman from The Adventures of Ichabod and Mr. Toad",
  "Heidi Weinerman from Randy Cunningham: 9th Grade Ninja",
  "Heihei the Rooster from Moana",
  "Hekapoo from Star vs. the Forces of Evil",
  "Helga Sinclair from Atlantis: The Lost Empire",
  "Hen Wen from The Black Cauldron",
  "Henry Fenner from The Princess and the Frog",
  "Hera from Hercules",
  "Herb Muddlefoot from Darkwing Duck",
  "Hercules from Hercules",
  "Hermes from Hercules",
  "Hieronymus Bump from The Owl House",
  "Hiram Flaversham from The Great Mouse Detective",
  "Hiro Hamada from Big Hero 6",
  "Hit Cat the English Cat from The Aristocats",
  "Honey Lemon from Big Hero 6",
  "Honker Muddlefoot from Darkwing Duck",
  "Hook Hand from Tangled",
  "Hoonah from Brother Bear 2",
  "Hooty from The Owl House",
  "Hopediah \"Hop Pop\" Plantar from Amphibia",
  "Horace from Kick Buttowski: Suburban Daredevil",
  "Horace & Jasper from 101 Dalmatians",
  "Horace Horsecollar from The Plow Boy",
  "The Horned King from The Black Cauldron",
  "Howard Handupme from Dinosaurs",
  "Howard Weinerman from Randy Cunningham: 9th Grade Ninja",
  "Huey from Donald's Nephews",
  "Hugo from The Hunchback of Notre Dame",
  "Humbert the Huntsman from Snow White and the Seven Dwarfs",
  "Humphrey the Bear from Hold That Pose",
  "Hunter from The Owl House",
  "Hyacinth Hippo from Fantasia",
  "Iago from Aladdin",
  "Ian the Alligator from The Princess and the Frog",
  "Iandore \"Ian\" Lightfoot from Onward",
  "Ichabod Crane from The Adventures of Ichabod and Mr. Toad",
  "The Indian Big Chief from Peter Pan",
  "Iridessa from Disney Fairies",
  "Imelda Rivera from Coco",
  "Ivy Sundew from Amphibia",
  "J. Audubon Woodlore from Grin and Bear It",
  "J. Gander Hooter from Darkwing Duck",
  "J. Thaddeus Toad from The Adventures of Ichabod and Mr. Toad",
  "J. Worthington Foulfellow from Pinocchio",
  "J.P. Spamley from Ralph Breaks the Internet",
  "Jack-in-the-Box from Fantasia 2000",
  "Jack Skellington from The Nightmare Before Christmas",
  "Jackie Lynn Thomas from Star vs. the Forces of Evil",
  "Jackie Wackerman from Kick Buttowski: Suburban Daredevil",
  "Jackson \"Jaq\" Hopscotch from Cinderella",
  "Jafar from Aladdin",
  "Jake from The Rescuers Down Under",
  "Jane Porter from Tarzan",
  "Janna Ordonia from Star vs. the Forces of Evil",
  "Jeb the Goat from Home on the Range",
  "Jennifer \"Jenny\" Foxworth from Oliver & Company",
  "Jenny Wren from Silly Symphonies",
  "Jeremy Birnbaum from Star vs. the Forces of Evil",
  "Jerry Jumbeaux Jr. from Zootopia",
  "Jesse the Ram from Zootopia",
  "Jessica Rabbit from Who Framed Roger Rabbit",
  "Jim Dear from Lady and the Tramp",
  "Jill the Frog from Muppet Babies",
  "Jim Hawkins from Treasure Planet",
  "Jiminy Cricket from Pinocchio",
  "Jobless Joe from Fantasia 2000",
  "Jock from Lady and the Tramp",
  "Joe Giraffe from Silly Symphonies",
  "Joey Hippo from Silly Symphonies",
  "John Darling from Peter Pan",
  "John Smith from Pocahontas",
  "John Silver from Treasure Planet",
  "Johnny Appleseed from Melody Time",
  "José Carioca from Saludos Amigos",
  "Jubileena Bing-Bing from Wreck-It Ralph",
  "Judge Claude Frollo from The Hunchback of Notre Dame",
  "Judy Hopps from Zootopia",
  "June from House of Mouse",
  "Junior from The Jungle Book",
  "Junior the Buffalo from Home on the Range",
  "Kaa from The Jungle Book",
  "Kala from Tarzan",
  "Kanga from Winnie the Pooh and the Honey Tree",
  "Kat from The Ghost and Molly McGee",
  "Kata from Brother Bear 2",
  "Katrina Van Tassel from The Adventures of Ichabod and Mr. Toad",
  "Kekata the Medicine man from Pocahontas",
  "Kelly from Star vs. the Forces of Evil",
  "Kenai from Brother Bear",
  "Kendall Perkins from Kick Buttowski: Suburban Daredevil",
  "Kerchak from Tarzan",
  "Kermit the Frog from Muppet Babies",
  "Kikimora from The Owl House",
  "Kim Possible from Kim Possible",
  "The King from Cinderella",
  "King from The Owl House",
  "King Andrias Leviathan from Amphibia",
  "The King of Hearts from Alice in Wonderland",
  "King Candy/Turbo from Wreck-It Ralph",
  "King Eiddileg from The Black Cauldron",
  "King Hubert from Sleeping Beauty",
  "King Kashekim Nedakh from Atlantis: The Lost Empire",
  "King Leonidas from Bedknobs and Broomsticks",
  "King Louie from The Jungle Book",
  "King Richard from Robin Hood",
  "King Roland II from Sofia the First",
  "King Stefan from Sleeping Beauty",
  "King Triton from The Little Mermaid",
  "Kirby from Chicken Little",
  "Kit Cloudkicker from TaleSpin",
  "KnowsMore from Ralph Breaks the Internet",
  "Kocoum from Pocahontas",
  "Koda from Brother Bear",
  "Kohut from Wreck-It Ralph",
  "Krebbs from The Rescuers Down Under",
  "Kristoff from Frozen",
  "Kron from Dinosaur",
  "Kronk Pepikrankenitz from The Emperor's New Groove",
  "Kuzco from The Emperor's New Groove",
  "Lachesis from Hercules",
  "Lady from Lady and the Tramp",
  "Lady Avarius from Star vs. the Forces of Evil",
  "Lady Kluck from Robin Hood",
  "Lady Mouse from The Great Mouse Detective",
  "Lady Olivia from Amphibia",
  "Lady Tremaine from Cinderella",
  "Lafayette the Basset Hound from The Aristocats",
  "Lampwick from Pinocchio",
  "Larry the Duck from Home on the Range",
  "Lars from 101 Dalmatians II: Patch's London Adventure",
  "Launchpad McQuack from DuckTales",
  "Laverne from The Hunchback of Notre Dame",
  "Lawrence the Valet from The Princess and the Frog",
  "Le Fou from Beauty and the Beast",
  "Lefty from Meet the Robinsons",
  "Lekmet from Star vs. the Forces of Evil",
  "Leonard Helperman from Teacher's Pet",
  "Leopold Loggle from Amphibia",
  "LePlume from Belle's Magical World",
  "Lewis from Meet the Robinsons",
  "Li Shang from Mulan",
  "Libby Stein-Torres from The Ghost and Molly McGee",
  "Lil Bad Wolf from The Porker's Court",
  "Lil Lightning from 101 Dalmatians II: Patch's London Adventure",
  "Lilith Clawthorne from The Owl House",
  "Lilo Pelekai from Lilo & Stitch",
  "Ling from Mulan",
  "The Liquidator from Darkwing Duck",
  "Little Debbie from Ralph Breaks the Internet",
  "Little John from Robin Hood",
  "Little Noi from Raya and the Last Dragon",
  "Little Toot from Melody Time",
  "Mr. Litwak from Wreck-It Ralph",
  "Lizzy from Meet the Robinsons",
  "Lizzy Griffiths from Tinker Bell and the Great Fairy Rescue",
  "Lord Dominator from Wander Over Yonder",
  "Lord Hater from Wander Over Yonder",
  "Louie from Donald's Nephews",
  "Louie the Hot Dog Man from Oliver & Company",
  "Louis the Alligator from The Princess and the Frog",
  "Lucifer the Cat from Cinderella",
  "Lucille Krunklehorn from Meet the Robinsons",
  "Lucky from One Hundred and One Dalmatians",
  "Lucky Jack from Home on the Range",
  "Ludo Avarius from Star vs. the Forces of Evil",
  "Ludwig Von Drake from An Adventure In Color",
  "Luke from The Rescuers",
  "Lumière from Beauty and the Beast",
  "Luz Noceda from The Owl House",
  "Ma Beagle from DuckTales",
  "Mabel Pines from Gravity Falls",
  "Mad Hatter from Alice in Wonderland",
  "Madame Adelaide Bonfamille from The Aristocats",
  "Madame Medusa from The Rescuers",
  "Madam Mim from The Sword in the Stone",
  "Madame Upanova from Fantasia",
  "Maddie Flour from Amphibia",
  "Madellaine from The Hunchback of Notre Dame II",
  "Maggie from Home on the Range",
  "Magic Carpet from Aladdin",
  "The Magic Mirror from Snow White and the Seven Dwarfs",
  "Magica De Spell from DuckTales",
  "Mahra the Baboon from Jungle Cubs",
  "Maid Marian from Robin Hood",
  "Major the Horse from Cinderella",
  "Maleficent from Sleeping Beauty",
  "Malina from The Emperor's New School",
  "Mama Heffalump from Pooh's Heffalump Movie",
  "Mama Odie from The Princess and the Frog",
  "Man the Hunter from Bambi",
  "Marahute from The Rescuers Down Under",
  "March Hare from Alice in Wonderland",
  "Marco Diaz from Star vs. the Forces of Evil",
  "Marcy Wu from Amphibia",
  "Maria Media from Big City Greens",
  "Marie from The Aristocats",
  "Mariposa \"Marco Jr.\" Diaz from Star vs. the Forces of Evil",
  "Markowski from Wreck-It Ralph",
  "Marlon the Alligator from The Princess and the Frog",
  "Mary Darling from Peter Pan",
  "Mary Poppins from Mary Poppins",
  "The Matchmaker from Mulan",
  "Matriarch Elephant from Dumbo",
  "Mattholomule from The Owl House",
  "Maui from Moana",
  "Maurice from Beauty and the Beast",
  "Max Goof from Goof Troop",
  "Max Hare from The Tortoise and the Hare",
  "Maximus from Tangled",
  "May from House of Mouse",
  "Mayor Lionheart from Zootopia",
  "Mayor Toadstool from Amphibia",
  "Mechanicles from Aladdin (TV series)",
  "Meeko from Pocahontas",
  "Megabyte Beagle from DuckTales",
  "Megara from Hercules",
  "Megavolt from Darkwing Duck",
  "Melinda from Fantasia",
  "Melpomene from Hercules",
  "Melvin from Chicken Little",
  "Mena from Bambi II",
  "Merlin from The Sword in the Stone",
  "Merlock the Magician from DuckTales",
  "Merryweather from Sleeping Beauty",
  "Mertle Edmonds from Lilo & Stitch",
  "Meteora Butterfly from Star vs. the Forces of Evil",
  "Michael Darling from Peter Pan",
  "Mickey Mouse from Steamboat Willie",
  "Mickey Mouse as Sorcerer’s Apprentice from Fantasia",
  "Mike the Microphone from House of Mouse",
  "Mildred from Meet the Robinsons",
  "Milo Murphy from Milo Murphy's Law",
  "Milo Thatch from Atlantis: The Lost Empire",
  "Mina Loveberry from Star vs. the Forces of Evil",
  "Mindy from Bolt",
  "Minnie Mouse from Plane Crazy",
  "Minty Zaki from Wreck-It Ralph",
  "Mirage from Aladdin (TV series)",
  "Miranda Wright from Bonkers",
  "Miss Bianca from The Rescuers",
  "Miss Kitty from The Great Mouse Detective",
  "Miss Lightfoot from The Ghost and Molly McGee",
  "Miss Nettle from Sofia the First",
  "Miss Piggy from Muppet Babies",
  "Miss Skullnick from Star vs. the Forces of Evil",
  "Mittens from Bolt",
  "Moana from Moana",
  "Mochi from Big Hero 6",
  "Moley from The Adventures of Ichabod and Mr. Toad",
  "Molly Cunningham from TaleSpin",
  "Molly McGee from The Ghost and Molly McGee",
  "Monica Devertebrae from Dinosaurs",
  "Monsieur D'Arque from Beauty and the Beast",
  "Monstro from Pinocchio",
  "Monterey Jack from Chip 'n Dale Rescue Rangers",
  "Moon Butterfly from Star vs. the Forces of Evil",
  "Morcupine Porcupine from Chicken Little",
  "Morgana from The Little Mermaid II: Return to the Sea",
  "Morgana McCawber from Darkwing Duck",
  "Morph from Treasure Planet",
  "Mortimer Mouse from Mickey's Rival",
  "Morty Fieldmouse from Mickey's Steam Roller",
  "Mother Gothel from Tangled",
  "Mother Rabbit from Robin Hood",
  "Mouth from Kick Buttowski: Suburban Daredevil",
  "Mowgli from The Jungle Book",
  "Mozenrath from Aladdin (TV series)",
  "Mr. Arrow from Treasure Planet",
  "Mr. Big from Zootopia",
  "Mr. Flour from Amphibia",
  "Mr. Jolly from Teacher's Pet",
  "Mr. Lizard from Dinosaurs",
  "Mr. Pettibone from Mickey Mouse Clubhouse",
  "Mr. Pulman from Dinosaurs",
  "Mr. Smee from Peter Pan",
  "Mr. Snoops from The Rescuers",
  "Mr. Stork from Dumbo",
  "Mr. Willerstein from Meet the Robinsons",
  "Mr. Woolensworth from Chicken Little",
  "Mr. Yama from Big Hero 6",
  "Mrs. Calloway from Home on the Range",
  "Mrs. Featherby from DuckTales",
  "Mrs. Hasagawa from Lilo & Stitch",
  "Mrs. Judson from The Great Mouse Detective",
  "Mrs. Jumbo from Dumbo",
  "Mrs. Otterton from Zootopia",
  "Mrs. Possum from Bambi",
  "Mrs. Potts from Beauty and the Beast",
  "Mrs. Quail from Bambi",
  "Ms. Chicarelli from Kick Buttowski: Suburban Daredevil",
  "Mufasa from The Lion King",
  "Mulan from Mulan",
  "Mungo from Tarzan",
  "Mushu from Mulan",
  "Nakoma from Pocahontas",
  "Nala from The Lion King",
  "Namaari from Raya and the Last Dragon",
  "Nana from Peter Pan",
  "Nancy Green from Big City Greens",
  "Nancy Tremaine from Enchanted",
  "Nani Pelekai from Lilo & Stitch",
  "Nanny from One Hundred and One Dalmatians",
  "Napoleon the Bloodhound from The Aristocats",
  "Nasira from Aladdin in Nasira's Revenge",
  "Nathaniel from Enchanted",
  "Ned from Earth to Ned",
  "Ned the Baboon from Jungle Cubs",
  "Neera from Dinosaur",
  "NegaDuck from Darkwing Duck",
  "Nemo from Finding Nemo",
  "Nessus from Hercules",
  "Nibs from Peter Pan",
  "Nicholas \"Nick\" P. Wilde from Zootopia",
  "Nita from Brother Bear 2",
  "Nurse Mouse from The Rescuers Down Under",
  "Nutsy the Vulture from Robin Hood",
  "Oaken from Frozen",
  "The Octopus from Return to Never Land",
  "Officer Keys from Big City Greens",
  "Olaf from Frozen",
  "Oliver from Oliver & Company",
  "Olivia Flaversham from The Great Mouse Detective",
  "Ollie the Pig from Home on the Range",
  "Omnitraxus Prime from Star vs. the Forces of Evil",
  "Onus from Treasure Planet",
  "Orange Bird from Foods and Fun: A Nutrition Adventure",
  "Orddu from The Black Cauldron",
  "Orgoch from The Black Cauldron",
  "Ortensia from The Banker's Daughter",
  "Orville from The Rescuers",
  "Orwen from The Black Cauldron",
  "Oskar Greason from Star vs. the Forces of Evil",
  "Oswald the Lucky Rabbit from Trolley Troubles",
  "Otto from Robin Hood",
  "Owl from Winnie the Pooh and the Honey Tree",
  "Pacha from The Emperor's New Groove",
  "Pain and Panic from Hercules",
  "Panchito Pistoles from The Three Caballeros",
  "Pantsy from Kick Buttowski: Suburban Daredevil",
  "Pascal from Tangled",
  "Patch from One Hundred and One Dalmatians",
  "Pearl Gesner from Home on the Range",
  "Peg from Lady and the Tramp",
  "Peg Pete from Goof Troop",
  "Pegasus from Hercules",
  "Penguin Waiters from Mary Poppins",
  "Penn Zero from Penn Zero: Part-Time Hero",
  "Penny from One Hundred and One Dalmatians",
  "Penny from The Rescuers",
  "Penny from Bolt",
  "Penny's Mom from Bolt",
  "Pepper Ann Pearson from Pepper Ann",
  "Peppo the Italian Cat from The Aristocats",
  "Percival C. McLeach from The Rescuers Down Under",
  "Percy from Pocahontas",
  "Perdita from 101 Dalmatians",
  "Periwinkle from Secret of the Wings",
  "Perry Potter from The Owl House",
  "Perry the Platypus from Phineas and Ferb",
  "Pete from Alice Solves the Puzzle",
  "Pete McGee from The Ghost and Molly McGee",
  "Pete Junior from Goof Troop",
  "Peter Pan from Peter Pan",
  "Peter Pan from Return to Never Land",
  "Peter Pig from The Wise Little Hen",
  "The Phantom Blot from DuckTales",
  "Philoctetes from Hercules",
  "Philippe the Horse from Beauty and the Beast",
  "Phineas Flynn from Phineas and Ferb",
  "Piglet from Winnie the Pooh and the Blustery Day",
  "Pinocchio from Pinocchio",
  "Pip from Enchanted",
  "Pistol Pete from Goof Troop",
  "Plio from Dinosaur",
  "Pluto from The Chain Gang",
  "Pocahontas from Pocahontas",
  "Poe De Spell from DuckTales",
  "Polly Petunia Plantar from Amphibia",
  "Pom-Pom from Cinderella II: Dreams Come True",
  "Pongo from 101 Dalmatians",
  "Pony Head from Star vs. the Forces of Evil",
  "Powerline from A Goofy Movie",
  "Practical Pig from Three Little Pigs",
  "Preston B. Whitmore from Atlantis: The Lost Empire",
  "Pretty Boy from Teacher's Pet",
  "Prince from Snow White and the Seven Dwarfs",
  "Prince Charming from Cinderella",
  "Prince Edward from Enchanted",
  "Prince Eric from The Little Mermaid",
  "Prince Hans from Frozen",
  "Prince James from Sofia the First",
  "Prince John from Robin Hood",
  "Prince Naveen from The Princess and the Frog",
  "Prince Phillip from Sleeping Beauty",
  "Princess from One Hundred and One Dalmatians",
  "Princess Amber from Sofia the First",
  "Princess Eilonwy from The Black Cauldron",
  "Princess Jasmine from Aladdin",
  "Princess Kidagakash from Atlantis: The Lost Empire",
  "Principal Mazur from A Goofy Movie",
  "Principal Skeeves from Star vs. the Forces of Evil",
  "Prissy the Elephant from Dumbo",
  "Professor Abominable from The Owl House",
  "Professor Norton Nimnul from Chip 'n Dale Rescue Rangers",
  "Professor Ratigan from The Great Mouse Detective",
  "Pronk Oryx-Antlerson from Zootopia",
  "Prudence from Cinderella II: Dreams Come True",
  "Pua from Moana",
  "Pumbaa from The Lion King",
  "Pyro from Ralph Breaks the Internet",
  "Quackerjack from Darkwing Duck",
  "Quasimodo from The Hunchback of Notre Dame",
  "Queen from Tangled Ever After",
  "Queen Clarion from Disney Fairies",
  "Queen Grimhilde from Snow White and the Seven Dwarfs",
  "Queen Leah from Sleeping Beauty",
  "Queen Miranda from Sofia the First",
  "Queen Mousetoria from The Great Mouse Detective",
  "Queen Narissa from Enchanted",
  "The Queen of Hearts from Alice in Wonderland",
  "Rabbit from Winnie the Pooh and the Honey Tree",
  "Rachel from Fantasia 2000",
  "Rafael Diaz from Star vs. the Forces of Evil",
  "Rafiki from The Lion King",
  "Rajah from Aladdin",
  "Rancis Fluggerbutter from Wreck-It Ralph",
  "Randall \"Randy\" Cunningham from Randy Cunningham: 9th Grade Ninja",
  "Rapunzel from Tangled",
  "Rashida Remington from Big City Greens",
  "Ratigan from The Great Mouse Detective",
  "Ratty from The Adventures of Ichabod and Mr. Toad",
  "Ray the Firefly from The Princess and the Frog",
  "Raya from Raya and the Last Dragon",
  "Razoul from Aladdin",
  "Rebecca Cunningham from TaleSpin",
  "Red from The Rescuers Down Under",
  "Remy Remington from Big City Greens",
  "Reuben (Experiment 625) from Stitch! The Movie",
  "Rhino from Bolt",
  "Rhoda Dendron from Darkwing Duck",
  "Rhombulus from Star vs. the Forces of Evil",
  "Rico from Home on the Range",
  "The Ringmaster from Dumbo",
  "Rita from Oliver & Company",
  "River Butterfly from Star vs. the Forces of Evil",
  "Rizzo the Rat from Muppet Babies",
  "Robert \"Bobby\" Zimuruski from A Goofy Movie",
  "Robert Mark \"Robbie\" Sinclair from Dinosaurs",
  "Robin Hood from Robin Hood",
  "Robin the Frog from Muppet Babies",
  "Roger Rabbit from Who Framed Roger Rabbit",
  "Roger Radcliffe from 101 Dalmatians",
  "Rolly from One Hundred and One Dalmatians",
  "Ronaldo from Kick Buttowski: Suburban Daredevil",
  "Ron Stoppable from Kim Possible",
  "Roo from Winnie the Pooh and the Honey Tree",
  "Roquefort the Mouse from The Aristocats",
  "Roscoe from Oliver & Company",
  "The Rose from Alice in Wonderland",
  "Rosetta from Disney Fairies",
  "Rowlf the Dog from Muppet Babies",
  "Roxanne from A Goofy Movie",
  "Roy Danger Hess from Dinosaurs",
  "Ruby from Lady and the Tramp II: Scamp's Adventure",
  "Rufus from The Rescuers",
  "Rufus from Kim Possible",
  "Runt of the Litter from Chicken Little",
  "Russell Remington from Big City Greens",
  "Rusty the Dog from Home on the Range",
  "Rutt and Tuke from Brother Bear",
  "Sadie Croaker from Amphibia",
  "Sadira from Aladdin (TV series)",
  "Sally ragdoll from The nightmare before Christmas",
  "Sam Flynn from Tron: Legacy",
  "Sam the Sheriff from Home on the Range",
  "Samson the Horse from Sleeping Beauty",
  "Sarabi from The Lion King",
  "Sarafina from The Lion King",
  "Sarah Hawkins from Treasure Planet",
  "Sarousch from The Hunchback of Notre Dame II",
  "Sasha Waybright from Amphibia",
  "Sashi Kobayashi from Penn Zero: Part-Time Hero",
  "Scar from The Lion King",
  "Scat Cat from The Aristocats",
  "Scooter from Muppet Babies",
  "Scratch from The Ghost and Molly McGee",
  "Scratchy from Lady and the Tramp II: Scamp's Adventure",
  "Scrooge McDuck from DuckTales",
  "Scroop from Treasure Planet",
  "Scuttle from The Little Mermaid",
  "Sebastian from The Little Mermaid",
  "Secretary Bird from Bedknobs and Broomsticks",
  "Sensei Brantley from Star vs. the Forces of Evil",
  "Sergeant Calhoun from Wreck-It Ralph",
  "Sgt. Tibbs from 101 Dalmatians",
  "Shan Yu from Mulan",
  "Shank from Ralph Breaks the Internet",
  "Shanti (The Girl) from The Jungle Book",
  "Sha-ron from Mulan II",
  "Sharon McGee from The Ghost and Molly McGee",
  "Sheela from The Ghost and Molly McGee",
  "Shego from Kim Possible",
  "Shenzi from The Lion King",
  "Shere Khan from The Jungle Book",
  "Sheriff of Nottingham from Robin Hood",
  "Shun Gon the Chinese Cat from The Aristocats",
  "Si & Am from Lady and the Tramp",
  "Sidney Tiberius \"Sid\" Turtlepuss from Dinosaurs",
  "Silvermist from Disney Fairies",
  "Simba from The Lion King",
  "Sir Ector from The Sword in the Stone",
  "Sir Giles from The Reluctant Dragon",
  "Sir Hiss from Robin Hood",
  "Sir Kay from The Sword in the Stone",
  "Sir Pellinore from The Sword in the Stone",
  "Sis Bunny from Robin Hood",
  "Sisu from Raya and the Last Dragon",
  "Sitka from Brother Bear",
  "Skara from The Owl House",
  "Skeeter from Muppet Babies",
  "Skippy Bunny from Robin Hood",
  "Sleepy from Snow White and the Seven Dwarfs",
  "Slightly from Peter Pan",
  "Smolder the Bear from Timon and Pumbaa",
  "Sneezy from Snow White and the Seven Dwarfs",
  "Snow White from Snow White and the Seven Dwarfs",
  "Snowanna Rainbeau from Wreck-It Ralph",
  "Princess Sofia from Sofia the First",
  "Soggy Joe from Amphibia",
  "Sorcerer’s Apprentice from Fantasia",
  "Sour Bill from Wreck-It Ralph",
  "Sparky from Lady and the Tramp II: Scamp's Adventure",
  "Sparky (Experiment 221) from Stitch! The Movie",
  "Sparky from Frankenweenie",
  "Specks (Glasses) Crow from Dumbo",
  "Speedy the Snail from Timon and Pumbaa",
  "Spike from Dinosaurs",
  "Spot from 101 Dalmatians: The Series",
  "Spot Helperman/Scott Leadready II from Teacher's Pet",
  "Sprig Plantar from Amphibia",
  "Spring Sprite from Fantasia 2000",
  "Squeaks the Caterpillar from The Fox and the Hound",
  "Stabbington brothers from Tangled",
  "Star Butterfly from Star vs. the Forces of Evil",
  "Statler and Waldorf from Muppet Babies",
  "Steelbeak from Darkwing Duck",
  "Stitch from Lilo & Stitch",
  "Stromboli from Pinocchio",
  "Stu Hopps from Zootopia",
  "Stumpy from Amphibia",
  "The Sultan from Aladdin",
  "Sultan the Footstool from Beauty and the Beast",
  "Suri from Dinosaur",
  "Sven from Frozen",
  "Swedish Chef from Muppet Babies",
  "Sweetums from Muppet Babies",
  "Swizzle \"The Swizz\" Malarkey from Wreck-It Ralph",
  "Sykes from Oliver & Company",
  "Sylvia from Wander Over Yonder",
  "Sylvia Marpole from An Extremely Goofy Movie",
  "Sylvia Sundew from Amphibia",
  "Tadashi Hamada from Big Hero 6",
  "Taffyta Muttonfudge from Wreck-It Ralph",
  "Tagalong Bunny from Robin Hood",
  "Tamatoa from Moana",
  "Tanana from Brother Bear",
  "Tank from An Extremely Goofy Movie",
  "Tank Muddlefoot from Darkwing Duck",
  "Tantor from Tarzan",
  "Tantor's Mother from Tarzan",
  "Taran from The Black Cauldron",
  "Tarzan from Tarzan",
  "Alex D. Linz[22] from ",
  "Taurus Bulba from Darkwing Duck",
  "Ted Betterhead from The Country Bears",
  "Terence from Disney Fairies",
  "Terk from Tarzan",
  "Terpsichore from Hercules",
  "Thalia from Hercules",
  "Thomas from Pocahontas",
  "Thomas O'Malley from The Aristocats",
  "Thug from Bolt",
  "Thumper from Bambi",
  "Thumper's Mother from Bambi",
  "Thunderbolt from 101 Dalmatians II: Patch's London Adventure",
  "Tiana from The Princess and the Frog",
  "Tibblet-Tibblie \"Tibbles\" Grimmhammer III from The Owl House",
  "Tiger Lily from Peter Pan",
  "Tigger from Winnie the Pooh and the Blustery Day",
  "Tillie Tiger from Silly Symphonies",
  "Tilly Green from Big City Greens",
  "Timon from The Lion King",
  "Timothy Q. Mouse from Dumbo",
  "Tina from Chicken Little",
  "Tinker Bell from Peter Pan",
  "Tino Tonitini from The Weekenders",
  "Tiny from Meet the Robinsons",
  "Tiny Nose from The Owl House",
  "Tip from The Little Mermaid II: Return to the Sea",
  "Tipo from The Emperor's New Groove",
  "Tito from Oliver & Company",
  "Toadie from Amphibia",
  "Tobias the Reluctant Dragon from The Reluctant Dragon",
  "Toby the Dog from The Great Mouse Detective",
  "Toby Tortoise from The Tortoise and the Hare",
  "Toby Turtle from Robin Hood",
  "Tod from The Fox and the Hound",
  "Toffee from Star vs. the Forces of Evil",
  "Tom from The Owl House",
  "Tom Lucitor from Star vs. the Forces of Evil",
  "Tong from Raya and the Last Dragon",
  "Tootles from Peter Pan",
  "Toots from Bonkers",
  "Toulouse from The Aristocats",
  "Tramp from Lady and the Tramp",
  "Travis from The Princess and the Frog",
  "Trigger the Vulture from Robin Hood",
  "Trusty from Lady and the Tramp",
  "Tug from Brother Bear",
  "Tui from Moana",
  "Tuk Tuk from Raya and the Last Dragon",
  "Turkey Lurkey from Chicken Little",
  "Tuskernini from Darkwing Duck",
  "Tuti from Amphibia",
  "Tweedledum and Tweedledee from Alice in Wonderland",
  "Two Fingers from The Princess and the Frog",
  "Uncle Art from Meet the Robinsons",
  "Uncle Waldo from The Aristocats",
  "Url from Dinosaur",
  "Ursula from The Little Mermaid",
  "Vanellope von Schweetz from Wreck-It Ralph",
  "Vanessa from The Little Mermaid",
  "Varian from Rapunzel's Tangled Adventure",
  "Vazquez from Big City Greens",
  "Veteran Cat from Bolt",
  "Victor from The Hunchback of Notre Dame",
  "Vidia from Disney Fairies",
  "Vincenzo \"Vinny\" Santorini from Atlantis: The Lost Empire",
  "Violet Parr from The Incredibles",
  "Virana from Raya and the Last Dragon",
  "Vixey from The Fox and the Hound",
  "Vladimir Goudenov Grizzlikof from Darkwing Duck",
  "Vanessa Doofenshmirtz from Phineas and Ferb",
  "Waddles from Gravity Falls",
  "Waffles from Goof Troop",
  "Wahn from Raya and the Last Dragon",
  "WALL-E from WALL-E",
  "Walliam \"One-Eyed Wally\" Ribbiton from Amphibia",
  "The Walrus from Alice in Wonderland",
  "Wander from Wander Over Yonder",
  "Warden Wrath from The Owl House",
  "Wasabi from Big Hero 6",
  "Webby Vanderquack from DuckTales",
  "Wendy Corduroy from Gravity Falls",
  "Wendy Darling from Peter Pan",
  "Wesley from Home on the Range",
  "White Rabbit from Alice in Wonderland",
  "Widow Tweed from The Fox and the Hound",
  "Wiggins from Pocahontas",
  "Wilbur from The Rescuers Down Under",
  "Wilbur Robinson from Meet the Robinsons",
  "Wilhelmina Packard from Atlantis: The Lost Empire",
  "Willie the Giant from Fun and Fancy Free",
  "Willow Park from The Owl House",
  "Winifred the Elephant from The Jungle Book",
  "Winkie the Barman from The Adventures of Ichabod and Mr. Toad",
  "Winnie the Pooh from Winnie the Pooh and the Honey Tree",
  "Winston from Oliver & Company",
  "Witherspoon from Belle's Magical World",
  "Woolter the Ram from Zootopia",
  "Wormwood the Raven from Sofia the First",
  "Wreck-It Ralph from Wreck-It Ralph",
  "Wynchel from Wreck-It Ralph",
  "XR from Buzz Lightyear of Star Command (TV series)",
  "Yao from Mulan",
  "Yar from Dinosaur",
  "Yax from Zootopia",
  "Yen Sid from Fantasia",
  "Yesss from Ralph Breaks the Internet",
  "Yo-Yo from Fantasia 2000",
  "Yzma from The Emperor's New Groove"
  ];

  var randomItem = nowPlaying[Math.floor(Math.random()*nowPlaying.length)];

      var displayElement = document.getElementById("display");
      displayElement.textContent = "Chris Pratt is now playing "+randomItem;
  }
